#!/usr/bin/env python3

from subprocess import run
from os import path, listdir, getcwd

# create nvim symbol link
print("Configure nvim")
if not path.exists(path.expandvars("$HOME/.config/nvim")):
    run(["ln", "-s", path.expandvars("$PWD/nvim"), path.expandvars("$HOME/.config/nvim")])

# create tools symbol link
print("Configure tools")
tools_path = path.join(path.dirname(__file__), "tools")
for tool in listdir(tools_path):
    if path.exists(path.expandvars(f"$HOME/.local/bin/{tool}")):
        continue
    print(f"Create symbol link for {tool} to ~/.local/bin/{tool}")
    run(["ln", "-s", path.join(tools_path, tool), path.expandvars(f"$HOME/.local/bin/{tool}")])


