[colors.bright]
black = "#505354"
blue = "#4c73e2"
cyan = "#899ca1"
green = "#b6e354"
magenta = "#9e6ffe"
red = "#ff5995"
white = "#f8f8f2"
yellow = "#feed6c"

[colors.normal]
black = "#121212"
blue = "#0e72ca"
cyan = "#465457"
green = "#82b414"
magenta = "#8c54fe"
red = "#f92672"
white = "#ccccc6"
yellow = "#fd971f"

[colors.primary]
background = "#171717"
foreground = "#ccccc6"
