#!/usr/bin/env python3
from optparse import OptionParser
import subprocess
import re
import os

parser = OptionParser()
(options, args) = parser.parse_args()

if len(args) != 1:
   exit(0) 

pattern = r'^((https://github.com/)?(?P<owner>[\w-]+)/)?(?P<repo>[\w-]+)$'

z = re.match(pattern, args[0])
if not z:
    exit(0)

owner = z.group("owner") or os.path.basename(os.path.normpath(os.getcwd()))
repo = z.group("repo")

path = os.path.expanduser("~/repo")
repo_dir = os.path.join(path, owner, repo)
subprocess.run(["gh", "repo", "clone", f"{owner}/{repo}", repo_dir])
subprocess.run(["zoxide", "add", repo_dir])

